### PR TITLE
Add service worker

### PR DESCRIPTION
**Pull request by marcusklaas**
Dit voegt offline support toe.

### CODE REVIEW

**Comment by JordyMoos** [comment]
Coool :D Thanks much appreciated.
I will check try the behavior when i am home,

One quick question: Will the sw.js file gets refreshed on the client if we deploy a new version of the sw.js? So like invalidating the old sw.js. I am not sure how that works.

**Comment by marcusklaas** [comment]
Yes, it should update the service worker whenever a new version is found.

**Comment by JordyMoos** [comment]
Awesome thanks! The code is looking good :+1:

**Comment by marcusklaas** [comment]
🔥 🔥

**Pull request merged**
